# Generated by Django 3.1.6 on 2021-02-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20210216_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(auto_now=True, verbose_name='transaction date'),
        ),
    ]
