# Generated by Django 3.1.6 on 2021-02-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_transaction_trans_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
