# Generated by Django 3.1.6 on 2021-02-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expenseitem_expenselist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
