# Generated by Django 3.1.6 on 2021-02-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20210220_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenselist',
            old_name='amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expenselist',
            old_name='category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='expenselist',
            old_name='date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='expenselist',
            old_name='merchant',
            new_name='merchant',
        ),
    ]
