# Generated by Django 3.1.6 on 2021-03-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_auto_20210221_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselist',
            name='date',
            field=models.DateField(verbose_name='Transaction Date'),
        ),
    ]
