# Generated by Django 3.1.6 on 2021-03-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
