# Generated by Django 3.1.6 on 2021-03-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_auto_20210305_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(related_name='expenses', to='expenses.Category'),
        ),
    ]
