# Generated by Django 3.1.6 on 2021-03-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_expense_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='categories',
            new_name='category',
        ),
    ]
