# Generated by Django 3.1.6 on 2021-03-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_auto_20210306_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.DeleteModel(
            name='ParentCategory',
        ),
    ]
