# Generated by Django 3.1.6 on 2021-05-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='category',
            field=models.ForeignKey(default='', limit_choices_to={'category': 'Deposit'}, on_delete=django.db.models.deletion.CASCADE, to='expenses.category'),
        ),
    ]
