# Generated by Django 3.1.6 on 2021-05-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_auto_20210502_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Index',
        ),
    ]
