# Generated by Django 3.1.6 on 2021-05-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0026_auto_20210502_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='category',
            field=models.ForeignKey(default='----', limit_choices_to={'category': 'Deposit'}, on_delete=django.db.models.deletion.CASCADE, to='expenses.category'),
        ),
    ]
