# Generated by Django 3.1.6 on 2021-05-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0027_auto_20210502_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposit',
            new_name='Deposits',
        ),
    ]
