# Generated by Django 3.1.6 on 2021-05-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0028_auto_20210502_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposits',
            new_name='Deposit',
        ),
    ]
