# Generated by Django 3.1.6 on 2021-05-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0029_auto_20210502_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='UserLogin',
        ),
    ]
