# Generated by Django 3.1.6 on 2021-05-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0032_auto_20210502_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='account_id',
        ),
    ]
