# Generated by Django 3.1.6 on 2021-05-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0036_auto_20210502_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.CharField(max_length=666),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='account',
            field=models.IntegerField(),
        ),
    ]
