# Generated by Django 3.1.6 on 2021-05-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0037_auto_20210502_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.IntegerField(),
        ),
    ]
